### ISSUE TITLE
Question about database

### ISSUE THREAD

**Issue by MostHated** [nilsramsperger/docker-nodebb#3]
Hey there,
    I see this is using Redis and you mentioned it is not the fastest but "safer". Is there a reason this isn't or cannot use a normal on-disk database like Mongo or whatever else it is capable of using? I have not used NodeBB yet but was looking to give it a go but would much prefer something that would be reliable and stable in case when I do try it I want to keep it. How difficult would it be to just use another DB with this setup?

Thanks,
-MH

**Comment by nilsramsperger** [comment]
Hi,

when I created this image, I wanted to have it the most easy way. Back then Redis seemed to be the lighter database compared to MongoDB. Just install and run. 
The default behavour of Redis is to work as an in memory DB, storing changes to disk from time to time. This might lead to partial data loss, if the container shuts down before a fresh change is persisted.
To mitigate that, I configured Redis to store every change directly to disk. Therefore it's safer but slower. I guess it won't be noticable, since Redis should use some kind of "write thru caching"-style mechanism. But it should have an impact on a heavy write load situation.
In terms of reliability, Redis shoild be perfectly ok with the given configuration.
Anyway, this image is ment to be used for rather small forums and people that do not want to build a complex app/DB container stack. At least the forum I'm hosting on it works like a charm for at least two years.
You could use an external database with this image by using the corresponding connection data in the NodeBB web installer. But that is not the intended way of usage. You would have an unused instance of Redis running inside the container.

From my point of view there are two options for you:
- If you want to use MongoDB, use or build a pure image for NodeBB and set up a stack.
- Use this image for a start and switch to a pure NodeBB/Redis stack when the need arises. 

Greetings
Nils

**Comment by MostHated** [comment]
Hey there,
    I definitely appreciate the detailed reply. I had never known that Redis did persist to disk on it's own, I always thought it was strictly an in memory db. That is definitely a good thing to know. That being said, I spent some time since I asked this to start with a fresh setup using docker-compose, NodeBB, MongoDB, and Mongo-Express which I got working yesterday using Nginx reverse proxy. I had used docker plenty in the past, but typically the bare minimum to get something up and running, so I decided to do some additional research and introduced some named bound volumes for NodeBB and Mongo, a network bridge, and a few docker entrypoint scripts to create users in Mongo for Express as well as setting up the NodeBB config. It was working great last night until I decided to wipe it all out to test out the setup from scratch, now it keeps giving a me errors when trying to actually stand up NodeBB:

    [4567/22] - error: Your NodeBB schema is out-of-date. Please run the following command to bring your dataset up to spec:
    [4567/22] - error:     ./nodebb upgrade

I am pretty close with it though, probably something silly I just need to work out. Once I get this smoothed out though, now that I know Redis is capable of persistence, I might give that a go next. I like to try and learn several ways of doing something and it would be good knowledge to have. I could compare the two and just see what I end up liking best. I had just pulled premade containers from Mongo and nodebb/docker for the ones I am using now, but after I get it finished I want to come back and reference your Dockerfile and see about creating the container that way. Based on what you mentioned, it seems like the additional customization and flexibility might come in handy. 

Thanks again, I appreciate it!
-MH

**Comment by nilsramsperger** [comment]
You can just execute `./nodebb upgrade` on every container start. It adds some startup time, but you won't have problems with outdated DB schemata. If the DB is up to date, the script will just leave it be.

**Comment by MostHated** [comment]
Ah nice, good call. Looks like I was able to just add:

    command: bash -c "./nodebb upgrade"

to my docker-compose and it was able to do it. It just keeps looping after that with nodebb exited with code 0 and updating over and over, but at least that is one thing down, lol. 👍 
Appreciate it!
-MH


*** Edit - After it updated, I just commented out the command: and now it came back up and all is well.
Thanks again!

**Comment by nilsramsperger** [comment]
If you just use `./nodebb upgrade` as command, the container will execute just that and shut down afterwards. To update first and start NodeBB afterwards, try something like `./nodebb upgrade && node app.js`. That way the upgrade gets run first and when it succeeds, NodeBB gets started as a foreground process. So the container should stay alive.
