### ISSUE TITLE
how to manage my redis

### ISSUE THREAD

**Issue by rsgok** [nilsramsperger/docker-nodebb#7]
there seems to be some trouble connecting to the internal database Redis.
i unluckily forget my admin password and have no email reset method, are there ways to manage the database ?

**Comment by nilsramsperger** [comment]
With shell access to the machine runing the NodeBB container, the most easy way is to use the redis-cli bundeled to the redis installation. You can run `docker exec -it myNodeBB redis-cli`. Exchange 'myNodeBB' with the name you gave the container.

I guess the database entry you are looking for is identified by the key 'user:1'. You can show it's contents by issuing `hgetall user:1`. The user's password hash is listed somwhere in the output.
To set the password, use the following command: `hset user:1 password "newhash"`. Replace 'newhash' but keep the quotes.
Finally a restart of the container might be needed to make the change work.

**Comment by rsgok** [comment]
awesome! it works!

BTW, is it possible for other programs to use the internal redis handly?
for example i wanna use the nodebb user account data in other programs, so i got to verify the info in redis, do i have to exec the command (by code) "docker exec -it myNodeBB redis-cli"  at first? 

thx again!

**Comment by nilsramsperger** [comment]
Out of the box, the Redis inside the container only accepts internal connections. You could modify the `/etc/redis.conf` to allow external connections. To use that, create a Docker intenal network by `docker network create networkname`, attach the NodeBB container to it by `docker network connect networkname myNodeBB`and then setup a container with the remote programm with `--network networkname`within it's `docker create` command. You should be able to address the NodeBB container by name from inside the remote programm's one.
Use Docker's internal networking for this only, because the Redis has no password configured. Opening an external port would expose the database.

This approach could be used only for a proof of concept.
There is a best practice for Docker containers, stating to use only one process per container. I violated this for ease of use of my image. If you want to setup a stack with multiple programms using the database, you should consider splitting NodeBB and Redis in seperate containers.

**Comment by rsgok** [comment]
thanks a lot.
